### ISSUE TITLE
`#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by shanithkk** [trevor-crypto/pdotc#1]
While building the library it shows `#![feature]` may not be used on the stable release channel on **#![feature(const_fn_trait_bound)]** this feature

**Comment by trevor-crypto** [comment]
Hi @shanithkk, currently the library only supports the `nightly` rust toolchain

**Comment by trevor-crypto** [comment]
Ah I see now. This feature is not even used. Thanks for finding this.
